### ISSUE TITLE
hubblestack RPM should not require git

### ISSUE THREAD

**Issue by whackyhack** [hubblestack/hubble#202]
GITFS is just one of the methods to install profiles - perhaps not the method of choice for production systems, git should not be a hard requirement in RPM.

**Comment by fossam** [comment]
I agree. Having git as a package requirement is not ideal from deployment perspective since it pulls in lots of other dependencies.

However, gitfs is used for Hubble (and salt itself) that runs under salt management in production systems.

Packaging statically compiled git binary with Hubble and getting the code to use that binary has been on my Todo list for a while.

**Comment by basepi** [comment]
I have git as a dep purely because it's the most popular fileserver backend for salt, and thus is probably going to be the most popular for hubble. It's also one of the easiest dependencies to source.

I'd be fine with pulling a standalone git binary into the package. But I do not want to add additional install steps, forcing the user to install it manually.

**Comment by fossam** [comment]
Fixed in #363
