### ISSUE TITLE
hubble --version not working

### ISSUE THREAD

**Issue by yassingh** [hubblestack/hubble#464]
I am facing an issue with the newer hubble builds.
Actually I have faced this issue in 2.4.1 also . Now I am facing this issue in 2.4.5 also.

Sometimes ( most of the times ), "hubble --version" and "hubble --buildinfo" command don't give any output.

"hubble --version -vvv" also doesn't give any output.

However, if I add any random string in front of these commands , i get perfect output.

For example:
"hubble --version xyz" and "hubble --buildinfo 123" work fine.

This is a random issue. Haven't found any pattern yet.

**Comment by basepi** [comment]
We moved the daemonization of the process (and the check for existing hubble processes) earlier in the daemon. What's happening is hubble is aborting because the daemon is already running on the system. We need to add an explicit exception for `--version`, which should be pretty simple.

Note the reason it works if you add additional characters is because there *is* an exception already for single-function runs, such as `hubble test.ping` or `hubble hubble.top`. By adding the additional characters you make hubble think that's what's happening, even if it never gets that far because `--version` is executed first.

It's an easy fix, and I'll get it in later this week when I'm back from sick leave. (My appendix was removed yesterday)
