### ISSUE TITLE
Python-inotify can be bypassed with hard links

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#72]
_From @basepi on March 7, 2017 22:42_

_From @basepi on January 25, 2017 18:30_

[001-20170109-Hubble.pdf](https://github.com/hubblestack/pulsar/files/730609/001-20170109-Hubble.pdf)

The only solution we've come up with so far is using `os.walk` to manually create watches on all files in a tree, rather than relying on the directory watches that inotify uses.

_Copied from original issue: hubblestack/pulsar#60_

_Copied from original issue: hubblestack/hubble-salt#24_

**Comment by basepi** [comment]
https://jira.corp.adobe.com/browse/CSTTEAM-40632

**Comment by jettero** [comment]
Since we merged #328 and #332, I think this issue is all set now.

**Comment by fossam** [comment]
Can you describe your tests, @jettero ?

**Comment by jettero** [comment]
@fossam I have actual tests that I added to the git: https://github.com/hubblestack/hubble/blob/develop/tests/unittests/test_pulsar.py#L144

I tried to account for everything, but missed at least a few things (see #328 and #332).

I also run the hubble daemon and manually create folders and files and hardlink them out of there for testing purposes. Arguably there should be a test of that in the unit tests. I didn't think of it because I happen to know the file watches catch that and I trust that it works...
